### ISSUE TITLE
IE8 and Firefox 10 have different behavior with the Style (Paragraph) button.

### ISSUE THREAD

**Issue by nautskye** [html5cat/redactor-js#1]
To reproduce the issue on each browser:

Go to http://redactorjs.com

In the Redactor editor, highlight:  `Well, one day I went up in a balloon and the ropes got twisted`

In the toolbar, click the **&para;** button and choose `code`

Click the **&para;** button again and choose `Header 1`

In IE8, the code style and the Header 1 style will be applied to the selected text:
# `Well, one day I went up in a balloon and the ropes got twisted`

In Firefox 10, the Header 1 style will be applied to the selected text:
# Well, one day I went up in a balloon and the ropes got twisted

Which is the desired behavior?

**Comment by html5cat** [comment]
Goog question. I'd assume the desired behaviour is the one that you see in Firefox. Hardly ever you want to have an H1 in code. What do you think?

**Comment by nautskye** [comment]
I agree with you, I like the Firefox behavior better (one &para; style per selected text).

Thanks for writing redactor, I love how clean it is!

**Comment by html5cat** [comment]
I didn't write it, I'm just maintaining the repo. Checkout the readme
