### ISSUE TITLE
<pre> formating

### ISSUE THREAD

**Issue by honzahommer** [html5cat/redactor-js#12]
We have some troubles with < pre > formating. Redactor removes empty lines and gives on the beginning each line spaces.

<b>Input:</b>
< pre >This
is
my code< /pre>

<b>Output</b>
< pre >This is my code< /pre>

<i>or</i>

<b>Input is:</b>
< pre >This

is

my code< /pre>

<b>Output</b>
< pre >This< br / >
< br / >
  is< br / >
< br / >
  my code< /pre>

**Comment by websiddu** [comment]
+1

**Comment by werdender** [comment]
+1
