### ISSUE TITLE
Ability to move Image anchor points.

### ISSUE THREAD

**Issue by twoolie** [html5cat/redactor-js#15]
There is an image in the editor area, and I can resize it with the mouse, but there seems to be no way to either "select" the image or to move it's "anchor" in the case of floated images.

**Comment by bmla** [comment]
Yes. Once it's placed it can't be moved up, down and in between text :(

**Comment by iamkeir** [comment]
I'd like to see this added too. Perhaps a small icon/drag area in the top right corner?

**Comment by twoolie** [comment]
There should be a way to change it's float as well.

**Comment by marcusgreenwood** [comment]
I think dragging to move should be the default behaviour with resizing by dragging the bottom right corner.

**Comment by iamkeir** [comment]
@twoolie If you click on the image, you can change its float from the 'position' dropdown.

@marcusgreenwood I'd agree with you there.

**Comment by opes** [comment]
This would definitely be a nice addition.  I think @marcusgreenwood has the right implementation idea for it, too.

**Comment by ghost** [comment]
I think it would be VERY useful if the drag was default and resize only in bottom right corner, like @marcusgreenwood said

**Comment by marcusgreenwood** [comment]
+1

**Comment by tomvo** [comment]
if you don't need the resize function, like we do in our app, you can just disable, the resizeImage functionality and make the editor behave with default contenteditable functionality.

**Comment by ivanmorales** [comment]
I changed it up a bit to have the dragging be the default action.  I included a "Resize" button that puts toggles that mode.  I'm pretty new to GitHub, but it appears that the project isn't allowing Pull Requests.

**Comment by chrvadala** [comment]
+1

**Comment by tpaloka** [comment]
Absolutely a must feature!
+1 from here also.

**Comment by KerryJones** [comment]
+1 Definitely need this as @marcusgreenwood said
