### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tobidelius** [html5cat/redactor-js#16]
Hi and thx for an awesome editor.

Is there any more docs about image/file uploads? I can't find anything about organizing images in folders.

I'm also having some problem with displaying images. I only uses the thumbnails.

Is the a filebrowser built in? Like the one for images.

**Comment by bmla** [comment]
This is the documentation on image and file upload:
http://redactorjs.com/docs/images/
http://redactorjs.com/docs/files/

I suggest you use a server-side scripting language to upload and organize your files. 

<blockquote>
<p>
Javascript doesn't allow the implementation of images uploads. Therefore, this feature utilizes server-side languages, such as PHP (see Python + Django implementation from Patrick Altman).
</p>
<i><a href="http://redactorjs.com/docs/images/" target="_blank">http://redactorjs.com/docs/images/</a></i>
</blockquote>


A filebrowser is a lot like an imagebrowser :)
