### ISSUE TITLE
Improvements to image resizing, editing, moving

### ISSUE THREAD

**Issue by marcusgreenwood** [html5cat/redactor-js#18]
RedactorJS is absolutely amazing - by far the best and simplest WYSIWYG editor. Thank you so much for developing it!

There is one fairly important issue that I have been struggling with - which is image manipulation, particularly in webkit.

The resizing functionality is great but the lack of the ability to move images in webkit is slightly frustrating. Would it be possible to change the resizing code so that it is more similar to this?

http://ghosted.it/demo

The advantage is that resizing is done by dragging the corner which is more intuitive and it leaves the standard contenteditable functionality to be able to drag the image around the page - I realise this is far from perfect in webkit because it does not show the cursor but it is better than nothing. The ability to adjust the float by clicking the left/right arrow overlay on the image is also quite nice.

Finally, it would also be nice if it were more easily possible to replace the image editing modal window with a custom one. We have replaced the image insert modal by overriding the 'image' button in the toolbar (I'm not sure if this is the way you are supposed to do it) and it would be great if we could replace the image edit dialog in a similar manner.

THANKS

**Comment by jlnwcic** [comment]
Answer on your "lack of the ability to move images"
-1- mouse over the image and right-click
-2- chose cut
-3- put your cursor in the new spot you want the image
-4- right-click and chose paste
![cutpaste](https://f.cloud.github.com/assets/4250456/460584/b89cc84a-b422-11e2-90ef-94468187d29c.jpg)
