### ISSUE TITLE
Add custom element to 'formatting' dropdown

### ISSUE THREAD

**Issue by iamkeir** [html5cat/redactor-js#25]
Finding it tricky to add an additional block element to the formatting dropdown in the toolbar.

I can edit the redactor.js directly to add a new element (an `<h5>` for example) but I'd rather not influence the core code in this way.

Does anyone know if new elements can be aded to the formatting dropdown through the config?

Ideally, I'd like to be able to add custom elements such as:
'small print' = `<div class="smallprint"></div>`

Any ideas/pointers greatly appreciated.

K

**Comment by vjpr** [comment]
On initialise you could pass in a different `toolbar.dropdown` option.

```
var Redactor = function(element, options) {
  ...
  // Options
  this.opts = $.extend({
  ...
    toolbar: { dropdown: { ... } }
```

You could also try creating a plugin - its quite easy and you have access to everything.

**Comment by iamkeir** [comment]
Hey @vjpr - thanks for your input, I'll have a play and report back.

I also edited my OP as I hadn't formatted code correctly.
