### ISSUE TITLE
formattingTags setting not working?

### ISSUE THREAD

**Issue by caloggs** [html5cat/redactor-js#29]
Hi, I have been testing redactor in a project I am working on and am having difficulty getting the formattingTags setting to work. 

Below is the code I am using: 

$('#redactor-content').redactor({ 
        focus: true,
    wym: true,
    formattingTags: ['h1', 'h2'],
});

However when I click on the formatting dropdown it still shows all the original options. 

Downloading a fresh copy from this repo, editing index.html and adding the formattingTags setting still reproduces the issue. Anyone else having similar problems?

**Comment by robbl** [comment]
+1

I'm having the same issue — all other options do work fine for me.

**Comment by neghmurken** [comment]
Same here.
Setting the "formattingTags" option is ineffective.

**Comment by judev** [comment]
I also had this issue, it was because I had called redactor() on a `<section>` tag but redactor requires that it be a `<div>`.
I traced this to the internal `isParentRedactor()` function.
