### ISSUE TITLE
support for external toolbars

### ISSUE THREAD

**Issue by ggoforth** [html5cat/redactor-js#3]
Hello, we recently found your editor and it looks great!  Do you plan on supporting external toolbars in the future?  Or letting the user specify where to render the toolbar to?  I would imagine the api would look something like:

```
$('textarea').redactor({
    toolbar: {
        type: 'custom',
        renderTo: $('.someExternalContainer')
    }
});
```

We currently use TinyMCE with this kind of setup, but really like the simplicity of your offering!

**Comment by html5cat** [comment]
@ggoforth thanks for your input. We'll definitely your suggestion into account.

**Comment by bmla** [comment]
:+1: Can only support this suggestion! It would be very helpful.

Is there anyway to imitate this at the moment?
