### ISSUE TITLE
Styling inside `pre` tag shouldn't be allowed.

### ISSUE THREAD

**Issue by vjpr** [html5cat/redactor-js#30]
1. Create a line and make it italic.
2. Press return and set style to `Code`.
3. Type something then press enter.

Actual: A new pre element is added.

Expected: A newline should be added inside the pre element.

Also, when working within a pre element, all styles should be disabled.

**Comment by websiddu** [comment]
+1

**Comment by Jamie-StripeOLT** [comment]
+1

HTML tags are being created inside of pre-tags, when you edit document and save and then reload document all the tags are rendered to the page including loads of &nbsp; tags.
