### ISSUE TITLE
Polish special characters causing text formatting on Windows 

### ISSUE THREAD

**Issue by sheerun** [html5cat/redactor-js#34]
On polish keyboard when one click Alt+l, it is expected that `ł` character will be printed. For now the superscipt is applied to text. Pleas also check other polish keys: (Alt+zolcesaxn).

**Comment by chryssalid** [comment]
I have the issue on Chrome. On jquery page they say this is Chrome problem. To repair this modify redactor.js:

line 897 (keydown event) change:

<pre>
if (key === 90)
{
    if (this.opts.buffer !== false)
    {
        e.preventDefault();
        this.getBuffer();
    }
    else if (e.shiftKey)
    {
        this.shortcuts(e, 'redo');  // Ctrl + Shift + z
    }
    else
    {
        this.shortcuts(e, 'undo'); // Ctrl + z
    }
}
to
if (key === 90)
{
    if (this.opts.buffer !== false)
    {
        e.preventDefault();
        this.getBuffer();
    }
    else if (e.shiftKey)
    {
        this.shortcuts(e, 'redo');  // Ctrl + Shift + z
    }
    else
    {
        if (e.altKey === false) {
            this.shortcuts(e, 'undo'); // Ctrl + z
        }
    }
}
</pre>

for ALT+z issue, and line 922 add && e.altKey === false to else if for alt + l issue.

Tested for polish.
