### ISSUE TITLE
How can I add a dropdown button as a plugin

### ISSUE THREAD

**Issue by itamar** [html5cat/redactor-js#36]
Hi,
I'm trying to add a new button of special characters into redactor as a plugin.
I've got an array with the name of the char and it's value but I couldn't find any kind of example or guidance how to do it.

Any kind of help is welcome,
Itamaryu

**Comment by kroofy** [comment]
I'm trying to do a dropdown myself. But instead a color picker for certain elements.

This could be a good start:

```
  init: function() {
    var colors = {
      red: {
        title: 'Red',
        callback: function(obj, event, key) {
          console.log(obj, event, key);
          obj.insertHtml('Red color');
        }
      },
      blue: {
        title: 'Blue',
        callback: function(obj, event, key) {
          console.log(obj, event, key);
          obj.insertHtml('Blue color');
        }
      }
    };

    this.addBtn('customDropdown', 'Custom Dropdown', function(obj, event, key) {
      console.log(obj, event, key);
    }, colors);
  }
```

You could also add the className attribute to your Objects to add a class selector to them.
