### ISSUE TITLE
onChange event is not triggered on underlying textarea

### ISSUE THREAD

**Issue by sheerun** [html5cat/redactor-js#38]
After modifying text in redactor.js, and after focus is lost, the onChange event is not triggered on textarea, the redactor.js has been created on.

**Comment by prikha** [comment]
Got same nasty issues, it makes autosave functionality for the whole model very uncertain.

**Comment by willtonkin** [comment]
Is there anything within redactor that can be hooked into to offer the same functionality?

**Comment by prikha** [comment]
Seems like no and authors does not seems to be interested in it

**Comment by borodean** [comment]
I seems that the issue can be solved in the following way:

``` javascript
$('body').on('input keydown', '.redactor_textbox', function () {
    $(this).siblings('textarea').trigger('change');
});
```

Not enough elegant, but getting things done.

**Comment by prikha** [comment]
Cool, I`ll try it in a while
