### ISSUE TITLE
Pasting into empty redactor from Chrome 24 creates nested <p> tags

### ISSUE THREAD

**Issue by kjantzer** [html5cat/redactor-js#42]
Chrome was recently updated to version 24 and we've noticed that text copied from styled sources (the web, emails, word docs) and pasted into an empty redactor creates nested `<p>` tags.

**_expected result from pasting:**_

```
<p>pasted content</p>
<p>from an outside source</p>
```

**_result from chrome 24:**_

```
<p>
    <p>pasted content</p>
    <p>from an outside source</p>
</p>
```

You can see this in the screenshot below. This was taken from the [home page](http://imperavi.com/redactor/)

![code screenshot](http://cl.ly/image/1P3S0A3z3z2Y/redactor%20chrome%2024%20paste%20bug.png)

**Comment by kjantzer** [comment]
**_Correction:**_ appears to be a webkit issue, not just chrome. I'm also seeing this behavior in Safari (6.0.2)

Here is a hacky fix that I'm using. Put this code at the end of the `pasteCleanUp()` method

```
if ($.browser.webkit)
{

    html = this.getCode();

    // remove dirty p
    html = html.replace(/<p>(\n*)<p>/gi, '<p>');
    html = html.replace(/<\/p><\/p>/gi, '</p>');

    this.setCode(html);
}
```

Not very elegant, but at least it gets the job done for the time being!

**Comment by danotorrey** [comment]
Hello,
I am experiencing the same problem in RedactorJS. I think setting the "linebreaks" setting to true may resolve this problem.

http://imperavi.com/redactor/docs/settings/

I have not tested this on my own system, but the Linebreaks demo on the RedactorJS website seems to not add these extra <p> tags when pasting HTML into the code view. 

http://imperavi.com/redactor/examples/linebreaks/

**Comment by kjantzer** [comment]
The `linebreaks` option might appear to fix the issue, but line breaks may not be desired in which case I think pasted content should not be wrapped in `<p>` tags.
