### ISSUE TITLE
Ability to Customize Image Margin

### ISSUE THREAD

**Issue by jcypret** [html5cat/redactor-js#44]
It would be nice to have the ability to customize image margins on floats. The code currently adds inline styling to float the images and add margin: `'float': 'left', margin: '0 10px 10px 0'`

The problem I'm having is that those numbers are hard-coded in with no way to modify them outside of editing the source code. I've added the following to the imageSave method in order to use a css class to style the content instead of inline styles. 

```
if (floating === 'left')
{
  $(el).css({ 'float': 'left', margin: '0 10px 10px 0' }).removeClass().addClass('alignleft');
}
else if (floating === 'right')
{
  $(el).css({ 'float': 'right', margin: '0 0 10px 10px' }).removeClass().addClass('alignright');
}
else
{
  $(el).css({ 'float': 'none', margin: '0' }).removeClass().addClass('alignnone');
}
```

I would like to see in future versions, either the option to specify the margin that are used in a config files, or a move to classes which would allow for the stylesheets to handle appearance.

**Comment by mrdoinel** [comment]
I think that would be a great idea!
The best should have at least css classes attached to images so we can overwrite the css values in front-end.
