### ISSUE TITLE
air:true failure with jquery 1.9.0

### ISSUE THREAD

**Issue by rowdyroad** [html5cat/redactor-js#45]
There is an error when text has selected in redactor' textarea.

Uncaught TypeError: Cannot call method 'apply' of undefined
$.event.special.textselect.handler
st.event.dispatch jquery.js:2
y.handle

with jquery 1.8.2 everything in OK

MacOS 10.8.2/Chrome 24.0.1312.56

**Comment by tobidelius** [comment]
+1 This it critical for me.

**Comment by stas** [comment]
Second that.

**Comment by kroofy** [comment]
Have you guys tried the lastest version?

> Version 8.2.2 January 17, 2013
> jQuery 1.9 compatibility.

http://imperavi.com/redactor/log/

**Comment by tobidelius** [comment]
I just tried and it does not work. jQuery 1.8.2 works great.

**Comment by heyvito** [comment]
8.2.2 is still broken, same problem on Ubuntu 12.10/Chrome 24.0 and Windows 8/Chrome 24.0, jQuery 1.9.1

**Comment by html5cat** [comment]
Updated the code to version 8.2.2. Works good on OS X Chrome, Safari and Firefox. jquery-1.9.0

**Comment by stas** [comment]
@dybskiy no it's not. Just tested by downloading the zip file, does not work with any of 1.9.0 or 1.9.1
Thanks for taking a look.

**Comment by html5cat** [comment]
@stas please post more details to troubleshoot. Which OS/browser combo you are using? Which error are you getting?

**Comment by stas** [comment]
It's the same error as already described in the issue.
I'm on Chromium and Firefox (Ubuntu), `{air: true}` option fails for both.

**Comment by html5cat** [comment]
Sorry, I missed the {air: true} part :/ If it's critical for your project I'd recommend getting in touch with official support: http://imperavi.com/support/
