### ISSUE TITLE
Webkit browsers insert DIV after closing UL

### ISSUE THREAD

**Issue by sitesense** [html5cat/redactor-js#48]
Normally when creating a new line by pressing enter, a new paragraph is created.

If you press enter twice after an unordered list to create a new line, Webkit browsers will insert a DIV element instead of a paragraph.

There is a fix for this in the formatNewLine function, however if the element that you transform into the editor (in my case a div) already has a class name, the function won't work because the class name no longer matches in this line:

<pre><code>if (parent.nodeName === 'DIV' && parent.className === 'redactor_editor')</code></pre>

Changing this line as below will fix this issue:

<pre><code>if (parent.nodeName === 'DIV' && parent.className.indexOf('redactor_editor') >= 0)</code></pre>
 

There is also another issue in that depending on the css that the editor is using, Webkit browsers may insert more than an empty DIV. In my case the line below is inserted after a closing UL instead:

<pre><code>&lt;div&gt;&lt;span style="line-height: 18px;"&gt;&lt;br&gt;&lt;/span&gt;&lt;/div&gt;</code></pre>

Therefore this line never matches and the cleanup fails:

<pre><code>if (element.get(0).tagName === 'DIV' && (element.html() === '' || element.html() === '&lt;br&gt;'))</code></pre>

I don't think it's really necessary to check the contents of the new line, so perhaps we can safely replace this line with the code below:

<pre><code>if (element.get(0).tagName === 'DIV')</code></pre>

**Comment by agis** [comment]
@sitesense What browser/version are you using? Your first proposed fix didn't work for me. When I press enter after <ul> I get this markup:

```
<p>
  <ul>
    <li><font color="#404040">hi there</font></li>
  </ul>
  <div>
    should be paragraph
  </div>
</p>
```
