### ISSUE TITLE
Redactor inserting spans with inline styles

### ISSUE THREAD

**Issue by voodoo6** [html5cat/redactor-js#53]
Redactor appears to be occasionally inserting <span> tags with inline styles:

<span style="font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif; font-size: 15px; line-height: 1.45em;">  

We could really do with an option to prevent this from happening?

(using chrome 26)

**Comment by digicase** [comment]
I have the same problem too. Using Safari Version 6.0 (7536.25) and Redactor v8.2.3.

```
<li><span style="line-height: 16px;">Etiam at risus et justo dignissim congue. Donec congue lacinia dui, a porttitor lectus</span><li>
```

**Comment by PaulGrimshaw** [comment]
Hi, I also have this issue.

**Comment by agis** [comment]
Same issue here. Haven't got the time to look into it yet.

**Comment by ncapito** [comment]
Also am seeing this issue, am looking into it now.  Dont think there is a way to fix this, but if you have a missmatch between lineheights (css) it will insert the spans.  I removed " line-height: 1.45em !important;" on line 78 and it fixed it for me.  The other thing I am seeing is converting h2-> span <inline style> not sure hwo to get around that one.

**Comment by agis** [comment]
@ncapito yes, this fixes the issue, thanks. The other thing is that it inserts <font> tags right before the list elements, see #54.

**Comment by gnattali** [comment]
I guess this is rather a problem of webkit's contenteditable.
Here's a related link.

http://www.neotericdesign.com/blog/2013/3/working-around-chrome-s-contenteditable-span-bug

And I found that the solution on this link is not enough. It's not only span which can be inserted.

**Comment by agis** [comment]
The solution is to use a non-webkit browser :-1:

**Comment by Stephenitis** [comment]
This is still an issue with a client of mine

**Comment by scarfacedeb** [comment]
@Stephenitis, you can set `iframe: true` for now. It resolves the issue, but it's not ideal.
