### ISSUE TITLE
Using  predefined classes

### ISSUE THREAD

**Issue by sergeyklay** [html5cat/redactor-js#57]
Hi all!

How I can specify my predefined CSS-classes that should be used for example when inserting tables?

Thanks

**Comment by sergeyklay** [comment]
where is answer? at least something ..

**Comment by html5cat** [comment]
This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase.

Please download the latest version from http://imperavi.com/redactor/
