### ISSUE TITLE
Font size drop down list.

### ISSUE THREAD

**Issue by maheshhfs** [html5cat/redactor-js#58]
Hi...

I integrated redactor editor in my web application. But there are no any setting for font size drop down list. I wont font size values from 6,7,8,9......,96 like in word document font size drop down list. So, what i do?

Thanks in advance.
Mahesh

**Comment by jlnwcic** [comment]
I agree. Considering this app for a client, and they wouldn't use it without the ability to change font sizes.  What about a customizable toolbar like CKEditor where you just add the name of the toolbar item you want in the line for the toolbar in the code?

**Comment by jlnwcic** [comment]
Actually, you can get font alterations using the paragraph icon:
![fonts](https://f.cloud.github.com/assets/4250456/460546/b78b4950-b421-11e2-8acc-4129450f2068.jpg).
Also, to add font size (6,7,8,9), you might be able to add it to the default style section. If I use the app, I will try that because your idea is a good one.

**Comment by EpokK** [comment]
Use this plugin : 

``` javascript
if (!RedactorPlugins) var RedactorPlugins = {};

RedactorPlugins.fontsize = {
    init: function()
    {
        var fonts = [10, 11, 12, 14, 16, 18, 20, 24, 28, 30];
        var that = this;
        var dropdown = {};

        $.each(fonts, function(i, s)
        {
            dropdown['s' + i] = { title: s + 'px', callback: function() { that.setFontsize(s); } };
        });

        dropdown['remove'] = { title: 'Remove font size', callback: function() { that.resetFontsize(); } };

        this.buttonAdd( 'fontsize', 'Change font size', false, dropdown);
    },
    setFontsize: function(size)
    {
        this.inlineSetStyle('font-size', size + 'px');
    },
    resetFontsize: function()
    {
        this.inlineRemoveStyle('font-size');
    }
};
```

**Comment by maheshhfs** [comment]
Oh!...... Nice solution. 
I implement it and try to change font size.... But, I am confused in following two methods,
this.inlineSetStyle('font-size', size + 'px');
 this.inlineRemoveStyle('font-size');
 this two methods are not in the redactor plugin. So, i try to implement this methods but does not works properly.
So, Please can you have code for this methods then please send me......
Again thanks for your thinking.......

Best Regards,
Mahesh.

**Comment by maheshhfs** [comment]
Hi....
can you explore for the following two methods......
this.inlineSetStyle('font-size', size + 'px'); & this.inlineRemoveStyle('font-size');
