### ISSUE TITLE
Doesn't work in IE10

### ISSUE THREAD

**Issue by jlnwcic** [html5cat/redactor-js#59]
Just an FYI on compatibility:  Several functions of Redactor doesn't work in IE10.  The browser switches to compatibility mode.  When you try to do anything that requires a popup like image, link, video, table, etc, the stage goes dark and no popup. Anyone know of a workaround?
Untested in IE9 or 8.

**Comment by Jamie-StripeOLT** [comment]
Hi,
Are you using a website on your local area network? 
IE will default to compatibility mode for sites on a LAN.
You could include something like http://stackoverflow.com/questions/3726357/why-does-ie9-switch-to-compatibility-mode-on-my-website to force IE to use the latest mode that it can.
Cheers,
Jamie

**Comment by jlnwcic** [comment]
Good question. No, it's on a live site. Also tried the META idea with no success.
Thanks for the idea though

**Comment by francoisdiotte** [comment]
Same issue over here... Does'nt work at all for IE10... META doesnt work either...

HELP! I buy the developper package, this MUST work on IE for my client !!!!

**Comment by francoisdiotte** [comment]
jlnwcic did you solve the problem?

**Comment by SimonEast** [comment]
There appears to be no fix or workaround for IE 9 or 10. For others looking, it appears that Redactor is only tested on the latest version of all browsers (see [Requirements and installation](https://imperavi.com/redactor/docs/how-to-install/)) which means IE 11 only.
