### ISSUE TITLE
Can't hide toolbar after creating editor without one.

### ISSUE THREAD

**Issue by cameronlinden** [html5cat/redactor-js#61]
$(".rich-text textarea").redactor({ toolbar: false }) // no toolbars, as expected

// later ...

$(".rich-text textarea").redactor({ toolbar: true}) // no toolbars. not expected
$(".rich-text textarea").redactor() // no toolbars again.

**Comment by EpokK** [comment]
You can hide toolbar with `hide()` jQuery method like this:

```
 $(".rich-text textarea").redactor('getToolbar').hide();
```
