### ISSUE TITLE
zoom in/out doesn't work well with the toolbal. CSS Sprites problem in chrome

### ISSUE THREAD

**Issue by oma** [html5cat/redactor-js#64]
The toolbar doesn't zoom well in Chrome (Version 26.0.1410.65). It works in Firefox, scales perfectly with the zoom there. I haven't tested other browsers. I think it has to do with CSS sprites and padding between images. But I don't know this well enough so I'll just report it.

This is how it looks zoomed out:
![screen shot 2013-05-12 at 10 54 40 pm](https://f.cloud.github.com/assets/19511/493458/8b03bc56-bb46-11e2-81b0-796ba24ae263.png)

zoomed in:
![screen shot 2013-05-12 at 10 54 29 pm](https://f.cloud.github.com/assets/19511/493460/8ef2968e-bb46-11e2-8fec-f569af0ea31e.png)

And with no zoom. The correct look.
![screen shot 2013-05-12 at 10 55 20 pm](https://f.cloud.github.com/assets/19511/493457/76b35478-bb46-11e2-8ffe-c1b9a70026cf.png)

Keep up the great work guys!

**Comment by oma** [comment]
@dybskiy is this fixed?

**Comment by html5cat** [comment]
Hey. Not in this repo unfortunately.

This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase.

Please download the latest version from http://imperavi.com/redactor/

**Comment by html5cat** [comment]
Happy to transfer ownership if you want to maintain a fork.

**Comment by oma** [comment]
lol, sorry, I didn't realize that. Thanks anyways @dybskiy

**Comment by html5cat** [comment]
Yeah :) Thanks for understanding!
