### ISSUE TITLE
jQuery noConflict

### ISSUE THREAD

**Issue by EpokK** [html5cat/redactor-js#68]
I use Prototype JS as main JS library and I have integrate RedactorJS with jQuery in mode no conflict but i can't launch function like :

``` javascript
jQuery('#redactor').redactor('destroy');
```

OR

``` javascript
jQuery('#redactor').destroy();
```

_ERROR : Error: No such method "destroy" for Redactor_

Have you a solution to this problem?

[DEMO](http://plnkr.co/edit/GM09x3Uv3onpZgPzKKao)

**Comment by netdev-julien** [comment]
Same here.

**Comment by Capellaro** [comment]
Same problem here...

**Comment by ybert** [comment]
Same  for me...

**Comment by netdev-julien** [comment]
A workaround for 8.X :

``` javascript
var redactor_inst = jQuery('#redactor').redactor('getObject');
redactor_inst.destroyEditor();
```

And for 9.X

``` javascript
var redactor_inst = jQuery('#redactor').redactor('getObject').destroy();
```

**Comment by baur79** [comment]
thank for solution

**Comment by vercotux** [comment]
Didn't work for me. I get:

```
No such method "getObject" for Redactor
```

**Comment by vercotux** [comment]
So do I have to reopen an almost identical new bug report now?

**Comment by HandyAndyShortStack** [comment]
Getting the same behavior as @vercotux using 9.19

**Comment by reyneke-vosz** [comment]
The bug is still existing! 

```
No such method "getObject" for Redactor

No such method "destroy" for Redactor
```

Here's a snippet to check if redactor is initialized:

```
if (typeof $('#redactor').data('redactor') != 'undefined') {
    // redactor is initialized!
    $('#redactor').destroy();
}
```

**Comment by afuno** [comment]
How now to solve this problem? None of the options are appropriate.
