### ISSUE TITLE
Redactor v8.2.5 unminified source code

### ISSUE THREAD

**Issue by nadyarych** [html5cat/redactor-js#84]
Hi guys.
Is there any place where I can find redactor's unminified source code for 8.2.5 version?
Thanks.

**Comment by html5cat** [comment]
Hi,
This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase unfortunately.

Please download the latest version from http://imperavi.com/redactor/
