### ISSUE TITLE
It dosn't keep history correctly

### ISSUE THREAD

**Issue by mahdi87gh** [html5cat/redactor-js#85]
Hi.
Thanks for the great work you've done.
i ran into this problem
for example if i write this sequence of lines. 

this
is
a
test

I expect to undo remove each line one by one.
but it removes all lines except first line just by one undo

thanks

**Comment by romanzks** [comment]
+1

**Comment by html5cat** [comment]
Hi,
This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase unfortunately.

Please download the latest version from http://imperavi.com/redactor/
