### ISSUE TITLE
image editor only works when a new image is inserted

### ISSUE THREAD

**Issue by esperancaJS** [html5cat/redactor-js#87]
when i open the editor with pre written content the images don't seem to have any functionality

**Comment by marceloboeira** [comment]
I have the same problem.

**Comment by html5cat** [comment]
Hi,
This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase unfortunately.

Please download the latest version from http://imperavi.com/redactor/
