### ISSUE TITLE
Image Upload function?

### ISSUE THREAD

**Issue by daslicht** [html5cat/redactor-js#88]
Hi,
is there a way to have a function instead of a php file : 

```
imageUpload: function(){...}
```

?

**Comment by marceloboeira** [comment]
That would be interesting...

**Comment by daslicht** [comment]
froala has this feature: http://editor.froala.com/docs/callbacks#beforeFileUpload
I think summernote (free) either

**Comment by marceloboeira** [comment]
thanks!

**Comment by daslicht** [comment]
You are welcome :)

**Comment by html5cat** [comment]
Hi,
This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase unfortunately.

Please download the latest version from http://imperavi.com/redactor/
