### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by codebyzen** [html5cat/redactor-js#89]
var RLANG = {
    html: 'HTML',
    video: 'Вставить видео',
    image: 'Вставить изображение',
    table: 'Таблица',
    link: 'Ссылка',
    link_insert: 'Вставить ссылку',
    unlink: 'Убрать ссылку',
    formatting: 'Форматирование',
    paragraph: 'Параграф',
    quote: 'Цитата',
    code: 'Код',
    header1: 'Заголовок 1',
    header2: 'Заголовок 2',
    header3: 'Заголовок 3',
    header4: 'Заголовок 4',
    bold:  'Жирный',
    italic: 'Курсив',
    fontcolor: 'Цвет шрифта',
    backcolor: 'Цвет фона',
    unorderedlist: 'Список',
    orderedlist: 'Нумерованный список',
    outdent: 'Выступ',
    indent: 'Отступ',
    cancel: 'Отмена',
    insert: 'Вставить',
    save: 'Сохранить',
    _delete: 'Удалить',
    insert_table: 'Вставить таблицу',
    insert_row_above: 'Добавить строку над текущей',
    insert_row_below: 'Добавить строку под текущей',
    insert_column_left: 'Добавить колонку слева',
    insert_column_right: 'Добавить колонку справа',
    delete_column: 'Удалить колонку',
    delete_row: 'Удалить строку',
    delete_table: 'Удалить таблицу',
    rows: 'Строки',
    columns: 'Колонки',
    add_head: 'Добавить заголовок',
    delete_head: 'Удалить заголовок',
    title: 'Название',
    image_position: 'Позиция',
    none: 'Нет',
    left: 'Лево',
    right: 'Право',
    image_web_link: 'Ссылка на изображение',
    text: 'Текст',
    mailto: 'Email',
    web: 'URL',
    video_html_code: 'Добавить код видео',
    file: 'Вставить файл',
    upload: 'Загрузить',
    download: 'Скачать',
    choose: 'Выбрать',
    or_choose: 'Иди выбрать',
    drop_file_here: 'Перетащите файл сюда',
    align_left: 'Левое выравнивание',
    align_center: 'Центрирование',
    align_right: 'Правое выравнивание',
    align_justify: 'Выравнивание по ширине',
    horizontalrule: 'Горизонтальная линия',
    deleted: 'Удалено',
    anchor: 'Якорь',
    link_new_tab: 'Открыть ссылку в новом окне',
    underline: 'Подчеркивание',
    alignment: 'Выравнивание'
};

**Comment by html5cat** [comment]
Hi,
This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase unfortunately.

Please download the latest version from http://imperavi.com/redactor/
