### ISSUE TITLE
Copy & Paste 

### ISSUE THREAD

**Issue by atmediauk** [html5cat/redactor-js#91]
I copy and paste text from say a bbc.co.uk news article into the http://imperavi.com/redactor/ example here and it preserves the paragraphs.

Yet the version of redactor im using on my own website does not preserve the paragraphs, but it does for word/pdf text.

Grr!
I'm using latest version.

**Comment by html5cat** [comment]
Hi,
This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase unfortunately.

Please download the latest version from http://imperavi.com/redactor/
