### ISSUE TITLE
Spanish translate

### ISSUE THREAD

**Issue by juancresc** [html5cat/redactor-js#92]
var RLANG = {
    html: 'HTML',
    video: 'Insertar video',
    image: 'Insertar imagen',
    table: 'Tabla',
    link: 'Link',
    link_insert: 'Insertar link',
    unlink: 'Eliminar link',
    formatting: 'Formato',
    paragraph: 'Párrafo',
    quote: 'Cita',
    code: 'Código',
    header1: 'Encabezado 1',
    header2: 'Encabezado 2',
    header3: 'Encabezado 3',
    header4: 'Encabezado 4',
    bold:  'Negrita',
    italic: 'Cursiva',
    fontcolor: 'Color de texto',
    backcolor: 'Color de fondo',
    unorderedlist: 'Lista sin orden',
    orderedlist: 'Lista numerada',
    outdent: 'Quitar sangría',
    indent: 'Agregar sangria',
    cancel: 'Cancelar',
    insert: 'Insertar',
    save: 'Guardar',
    _delete: 'Eliminar',
    insert_table: 'Insertar table',
    insert_row_above: 'Agregar fila debajo',
    insert_row_below: 'Agregar fila arriba',
    insert_column_left: 'Agregar columna a la izquierda',
    insert_column_right: 'Agregar columna a la derecha',
    delete_column: 'Eliminar columna',
    delete_row: 'Eliminar fila',
    delete_table: 'Eliminar tabla',
    rows: 'Filas',
    columns: 'Columnas',
    add_head: 'Agregar encabezado',
    delete_head: 'Eliminar encabezado',
    title: 'Título',
    image_position: 'Posición',
    none: 'Ninguno',
    left: 'Izquierda',
    right: 'Derecha',
    image_web_link: 'Imagen con link web',
    text: 'Texto',
    mailto: 'Email',
    web: 'URL',
    video_html_code: 'Código de video',
    file: 'Insertar archivo',
    upload: 'Subir',
    download: 'Descargar',
    choose: 'Elegir',
    or_choose: 'O elegir',
    drop_file_here: 'Soltar archivos aquí',
    align_left: 'Alinear a la izquierda',
    align_center: 'Centrar texto',
    align_right: 'Alinear a la derecha',
    align_justify: 'Justificar',
    horizontalrule: 'Insertar regla horizontal',
    deleted: 'Eliminado',
    anchor: 'Ancla',
    link_new_tab: 'Abrir link en ventana nueva',
    underline: 'Subrayado',
    alignment: 'Alineación'
};

**Comment by html5cat** [comment]
Hi,
This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase unfortunately.

Please download the latest version from http://imperavi.com/redactor/
