### ISSUE TITLE
Image resize as in http://imperavi.com/redactor/

### ISSUE THREAD

**Issue by juancresc** [html5cat/redactor-js#93]
It seems that image resizing has improved. 

You have a nice EDIT button on the center of the image and streching the image is nicer.

Can we get those updates?

**Comment by html5cat** [comment]
Hi,
This was a code-mirror originally and everything was awesome until the license change in May 29, 2012. Ever since then this has been basically an out-dated codebase unfortunately.

Please download the latest version from http://imperavi.com/redactor/
